# Site settings
title: John Buckley BA
email: johnbuckleyphotography@gmail.com
description: A blog in fulfillment of the Professional Photography BA at Edinburgh College
website: http://johnbuckleyphotography.uk
mobile: +44 7440 099518

baseurl: 
url:  # the base hostname & protocol for your site

# Social
twitter_username:
github_username:

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  cs:
    output: true
    permalink: /cs/:path/
  cpp:
    output: true
    permalink: /cpp/:path/
  psp:
    output: true
    permalink: /psp/:path/

exclude: [Gemfile*]

gems: [jekyll-paginate]